title: "Extras 2"
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics: true
theme: jekyll-theme-minimal
url: "https://viktor-chiarcos.github.io/extra2"
theme: "jekyll-theme-minimal"
encoding: UTF-8
